### ISSUE TITLE
分词和词性标注原理是什么？

### ISSUE THREAD

**Issue by qinghua2016** [thunlp/THULAC#10]
您好，看了您给的相关论文： Punctuation as Implicit Annotations for Chinese Word Segmentation. Computational Linguistics，和c++训练代码，感觉代码和论文讲的不一样，不明白您的代码的分词和词性标注原理是什么？能讲讲吗？@gzp9595

**Comment by gzp9595** [comment]
非常感谢您对THULAC的支持，我们这篇论文确实没有特别详细的讲解训练方法。我们的训练使用的是平均感知器算法：
![unnamed](https://cloud.githubusercontent.com/assets/12404413/20998172/0a8d12f0-bd47-11e6-9300-a60bb0c9848d.png)
