### ISSUE TITLE
segfault during training

### ISSUE THREAD

**Issue by WenchenLi** [thunlp/THULAC#11]
➜ 
```
THULAC git:(master) ✗ ./train_c pku_test.utf8.txt model_test 
separator: [/]
training file "pku_test.utf8.txt" scanned
DAT (double array TRIE) file "model_test_dat.bin" created
number of labels: 
number of features: 
235588
model file "model_test_model.bin" created
label file "model_test_label.txt" created
[1]    9169 segmentation fault (core dumped)  ./train_c pku_test.utf8.txt model_test

```
[pku_test.utf8.txt](https://1drv.ms/t/s!Ao_Ao41kyU6BgcldjK0KNBzYQ2opzA]. ) file is here. 

thanks

**Comment by gzp9595** [comment]
I can't open this file.

we use "/" as default separator, you can use "-s" change separator.

if the separator is "/", the training file should be 
我/r 爱/vm 北京/ns 天安门/ns

you can check you training file.

**Comment by WenchenLi** [comment]
thanks for pointing out. I get it.
