### ISSUE TITLE
北京市政府分割错误

### ISSUE THREAD

**Issue by alexlee728** [thunlp/THULAC#15]
北京市政府这些被分割成了    北京市   政府

**Comment by gzp9595** [comment]
您好，我觉得北京市政府被分割成了“北京市”“政府”从意义上没什么问题，我们平常说”市政府“是因为省略了前面对应的城市名字。如果是需要将北京市政府分割成”北京“”市政府“您可以使用相应的语料进行训练~

**Comment by qiaosiyi** [comment]
23333333333333333，你可以试试“北京市市政府”，本来这个让human分都有不同的理解
