### ISSUE TITLE
mac系统下make总是失败

### ISSUE THREAD

**Issue by xixiaoyao** [thunlp/THULAC#23]
执行make编译C++工程时错误如下：

> In file included from src/thulac.cc:7:
> src/thulac.h:18:5: warning: control reaches end of non-void function
>       [-Wreturn-type]
>     }
>     ^
> 25 warnings generated.
> Undefined symbols for architecture x86_64:
>   "_iconv", referenced from:
>       _main in thulac-444612.o
>   "_iconv_close", referenced from:
>       thulac::Chinese_Charset_Conv::~Chinese_Charset_Conv() in thulac-444612.o
>   "_iconv_open", referenced from:
>       thulac::Chinese_Charset_Conv::Chinese_Charset_Conv() in thulac-444612.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [thulac] Error 1

已经在.bash_profile里将g++和gcc给alias到了gnu gcc上，但是还是报clang错误。已经折腾整整两天了，望给思路，谢谢！

**Comment by gzp9595** [comment]
您好，我看报错的原因是因为Chinese_Charset_Conv()无法执行，缺少 iconv库~

祝好！


-- 
郭志芃
清华大学计算机科学与技术系
电话：18813046062
通信地址：北京市，海淀区，清华大学，紫荆公寓2号楼307B，邮编100084
邮箱：gzp9595@gmail.com

Guo Zhipeng
Department of Computer Science and Technology, Tsinghua University
Tel: 18813046062
Address: Room 307B, No. 2 Zijing Building, Tsinghua University, Beijing, 100084
Email: gzp9595@gmail.com

**Comment by xixiaoyao** [comment]
谢谢！
