### ISSUE TITLE
分词和词性标注速度

### ISSUE THREAD

**Issue by alpha19881007** [thunlp/THULAC#27]
官网公布的词性标注速度可以达到300KB/s，对应的标签数是多少？标签数对于词性标注速度影响很大，虽然预处理可以减少解码空间，但还是有限的。我这边测试时，标签数是342时，处理速度仅为27KB/s。相差太大，请问有人知道怎么解决吗？

**Comment by gzp9595** [comment]
您好，非常感谢使用thulac

官方公布的速度 是使用我们发布的模型测试时得到的结果，其标签数量大约为100左右；

由于程序在分词和词性标注过程中的算法复杂度为 O(n^2)，所以按照标签为342的时候，比发布的模型慢9倍左右

祝好！

发送自 Windows 10 版邮件应用

发件人: Wenqiang.xu
发送时间: 2017年9月26日 11:44
收件人: thunlp/THULAC
抄送: Subscribed
主题: [thunlp/THULAC] 分词和词性标注速度 (#27)

官网公布的词性标注速度可以达到300KB/s，对应的标签数是多少？标签数对于词性标注速度影响很大，虽然预处理可以减少解码空间，但还是有限的。我这边测试时，标签数是342时，处理速度仅为27KB/s。相差太大，请问有人知道怎么解决吗？

**Comment by alpha19881007** [comment]
非常感谢！
