### ISSUE TITLE
readme中有不良链接

### ISSUE THREAD

**Issue by ares89** [thunlp/THULAC#31]
在第二届国际汉语分词测评中，共有四家单位提供的测试语料（Academia Sinica、 City University 、Peking University 、Microsoft Research）, 在评测提供的资源icwb2-data中包含了来自这四家单位的训练集（training）、测试集（testing）, 以及根据各自分词标准而提供的相应测试集的标准答案（icwb2-data/scripts/gold）．在icwb2-data/scripts目录下含有对分词进行自动评分的perl脚本score。

icwb2-data 这个地址的链接，http://sighan.org/bakeoff2005/ 是个黄色网址

**Comment by gzp9595** [comment]
感谢提醒，已经更新网站地址
