### ISSUE TITLE
thulac  pro 在mac上的编译问题

### ISSUE THREAD

**Issue by LeZhengThu** [thunlp/THULAC#7]
直接make出现了Undefined symbols for architecture x86_64: "_libiconv"的问题，帮助文档里说“修改makefile文件，在编译命令中添加 -liconv ”，请问-liconv加在哪里？修改$(cxx) $(src_dir)/thulac.cc -o $(dst_dir)/thulac，变成$(cxx) $(src_dir)/thulac.cc -o $(dst_dir)/thulac -static -liconv重新编译，出现了新的error，“ld: library not found for -lcrt0.o”

**Comment by gzp9595** [comment]
$(cxx) $(src_dir)/thulac.cc -liconv -o $(dst_dir)/thulac
您好，这样增加即可~

**Comment by LeZhengThu** [comment]
谢谢回复，但是Undefined symbols for architecture x86_64: "_libiconv"的报错依然存在？

**Comment by gzp9595** [comment]
你可以试一下，自己的电脑上是否有这个库，或者C++版本比较低？

**Comment by LeZhengThu** [comment]
有的，/usr/local里面有libiconv的libiconv.2.4.0.dylib, libiconv.2.dylib, libiconv.dylib, libiconv.la这些g++的版本是4.9.3

**Comment by gzp9595** [comment]
您可以试一下将这几个文件链接到 /usr的相关目录线面，因为-l指令只在/usr下搜索的~
