### ISSUE TITLE
import thulac 后 分词和标注速度为什么特别慢

### ISSUE THREAD

**Issue by wangshang19911011** [thunlp/THULAC#9]
import thulac 后
thu1 = thulac.thulac("-seg_only")  #设置模式为行分词模式
thu2 = thulac.thulac("-deli /") #标注模式

thu1.cut(）
500KB的文字要4.63秒
thu2.cut()
标注模式也转不动

**Comment by gzp9595** [comment]
非常感谢您对THULAC的支持，我们现在python版本的运行速度确实比较慢，可能达不到做大规模数据的程度。我们也在持续修改和优化，也欢迎您加入~

如果想进行大规模数据处理，可以使用THULAC.so版本~
